# This workflow will install Python dependencies, build the package and then build the documentation.

name: Build documentation


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        create-args: >-
          python=3.9.15
        environment-file: ci-environment.yml
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install libopenmpi-dev
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
        pip install .
        pip install .[dev]
    - name: Install notebook requirements
      run: |
        sudo apt-get install pandoc
    - name: Build docs
      run: |
        sphinx-build -T -E -b html -d docs/build/doctrees ./docs docs/build/html